## The profile with cache requires mysql, redis, zookeeper, kafka and debezium.
## You can run `<jimmer_home>/example/env-with-cache/debezium/install.sh` to install them in docker

spring:

  # Redisson has been disabled in default profile, enable it in this profile
  autoconfigure:
    exclude: # Exclude nothing

  datasource:
    url: jdbc:mysql://localhost:3306/mystery_box
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:5100
      group-id: jimmer-demo/sql
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: MANUAL_IMMEDIATE

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect